# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Voting Rights
tagline:          ''
description:      'A 2020 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://DSSG-eiCompare.github.io"
baseurl:          "/voting_rights"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/DSSG-eiCompare/voting_rights/
